---
- name: Install required packages
  yum: name='{{ item }}' state=present
  with_items:
    - sysbench
    - fio
    - postfix
    - mailx

- name: Ensure Postfix is running
  service: name=postfix state=started enabled=yes

- name: Copy Git config
  copy: src=gitconfig dest=/root/.gitconfig mode=0700

- include: cpubench.yml

- include: memorybench.yml

- include: latencybench.yml

- include: fio_bench.yml
